# Generated by Django 3.2.8 on 2025-01-18 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_num', models.IntegerField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(blank=True, max_length=255)),
                ('transaction_date', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=255)),
                ('est_pickup_date', models.DateField(blank=True, null=True)),
                ('forfeit_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'transaction',
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('noteid', models.IntegerField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=255)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('transaction_num', models.ForeignKey(db_column='transaction_num', on_delete=django.db.models.deletion.CASCADE, to='pickup.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'note',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('itemid', models.IntegerField(primary_key=True, serialize=False)),
                ('desc', models.CharField(max_length=255)),
                ('picked_up_on', models.DateField(blank=True, null=True)),
                ('transaction_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pickup.transaction')),
            ],
            options={
                'db_table': 'item',
            },
        ),
    ]
